################################################################################
# Automatically-generated file. Do not edit!
################################################################################

ASM_UPPER_SRCS := 
O_SRCS := 
ELF_SRCS := 
SX_SRCS := 
LINKER_SCRIPT := 
JMP_UPPER_SRCS := 
P_UPPER_SRCS := 
SRC_SRCS := 
JMP_SRCS := 
FSY_UPPER_SRCS := 
PP_UPPER_SRCS := 
OBJ_UPPER_SRCS := 
ASM_SRCS := 
SX_UPPER_SRCS := 
O_UPPER_SRCS := 
S_UPPER_SRCS := 
ELF_UPPER_SRCS := 
C_UPPER_SRCS := 
OBJ_SRCS := 
S_SRCS := 
PP_SRCS := 
SRC_UPPER_SRCS := 
FSY_SRCS := 
P_SRCS := 
C_SRCS := 
JMP_DEPS := 
FSY_DEPS := 
C_UPPER_DEPS := 
SECONDARY_SIZE := 
SRC_UPPER_DEPS := 
P_UPPER_DEPS := 
S_DEPS := 
LST := 
PP_UPPER_DEPS := 
P_DEPS := 
FSY_UPPER_DEPS := 
C_DEPS := 
SRC_DEPS := 
JMP_UPPER_DEPS := 
PP_DEPS := 
SX_DEPS := 
ASM_UPPER_DEPS := 
SX_UPPER_DEPS := 
OBJS := 
SECONDARY_FLASH := 
ASM_DEPS := 
S_UPPER_DEPS := 
MAP := 

# Every subdirectory with source files must be described here
SUBDIRS := \
rzt/aws/amazon-freertos \
rzt/aws/amazon-freertos/freertos_kernel \
rzt/aws/amazon-freertos/freertos_kernel/portable/MemMang \
rzt/aws/amazon-freertos/libraries/freertos_plus/standard/freertos_plus_tcp/source \
rzt/aws/amazon-freertos/libraries/freertos_plus/standard/freertos_plus_tcp/source/portable/BufferManagement \
rzt/board/rzt2m_rsk \
rzt/fsp/src/bsp/cmsis/Device/RENESAS/Source/cr \
rzt/fsp/src/bsp/cmsis/Device/RENESAS/Source \
rzt/fsp/src/bsp/mcu/all \
rzt/fsp/src/bsp/mcu/all/cr \
rzt/fsp/src/bsp/mcu/rzt2m \
rzt/fsp/src/r_adc \
rzt/fsp/src/r_canfd \
rzt/fsp/src/r_cgc \
rzt/fsp/src/r_dmac \
rzt/fsp/src/r_dsmif \
rzt/fsp/src/r_elc \
rzt/fsp/src/r_ether_phy \
rzt/fsp/src/r_ether_selector \
rzt/fsp/src/r_ethsw \
rzt/fsp/src/r_gmac \
rzt/fsp/src/r_gpt \
rzt/fsp/src/r_icu \
rzt/fsp/src/r_icu_error \
rzt/fsp/src/r_icu_inter_cpu_irq \
rzt/fsp/src/r_iic_master \
rzt/fsp/src/r_ioport \
rzt/fsp/src/r_mtu3 \
rzt/fsp/src/r_mtu3_three_phase \
rzt/fsp/src/r_poe3 \
rzt/fsp/src/r_sci_uart \
rzt/fsp/src/r_shared_memory \
rzt/fsp/src/r_spi \
rzt/fsp/src/r_tsu \
rzt/fsp/src/rm_freertos_plus_tcp \
rzt/fsp/src/rm_freertos_port/cr \
rzt_gen \
src \

