#include "hal_data.h"
#include "new.h"
#define BOARD "ft21/boardmap_rzt2m.h" // TODO: need to move onto makefile
#include "cnc.h"
FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event)
    BSP_PLACE_IN_SECTION(".warm_start");
FSP_CPP_FOOTER

/*******************************************************************************************************************/ /**
                                                                                                                       * main() is generated by the FSP Configuration editor and is used to generate threads if an RTOS is used.  This function
                                                                                                                       * is called by main() when no RTOS is used.
                                                                                                                       **********************************************************************************************************************/
void hal_entry(void)
{
    /* TODO: add your own code here */
}

// For ISR
void R_IRQ1_isr(void)
{
    // ISR implementation here
}

void r_mtu_tgiv3_interrupt(void)
{
    // ISR code
}

void r_mtu_tgiv6_interrupt(void)
{
    // ISR code
}

void m_sci0_eri_interrupt(void)
{
}
void m_sci0_rxi_interrupt(void)
{
}
void m_sci0_txi_interrupt(void)
{
}
void m_sci0_tei_interrupt(void)
{
}
void r_enc_ch0_int_isr(void)
{
}
void r_enc_ch0_err_int_isr(void)
{
}
void r_enc_ch1_int_isr(void)
{
}
void r_enc_ch1_err_int_isr(void)
{
}

/*******************************************************************************************************************/ /**
                                                                                                                       * This function is called at various points during the startup process.  This implementation uses the event that is
                                                                                                                       * called right before main() to set up the pins.
                                                                                                                       *
                                                                                                                       * @param[in]  event    Where at in the start up process the code is currently at
                                                                                                                       **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
        /* Pre clock initialization */
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        if (NULL != g_bsp_pin_cfg.p_extend)
        {
            /* Configure pins. */
            R_IOPORT_Open(&g_ioport_ctrl, &g_bsp_pin_cfg);
        }
    }
}
