/* generated configuration header file - do not edit */
#ifndef R_MTU3_CFG_H_
#define R_MTU3_CFG_H_
#define MTU3_CFG_PARAM_CHECKING_ENABLE (BSP_CFG_PARAM_CHECKING_ENABLE)
#define MTU3_CFG_OUTPUT_SUPPORT_ENABLE (2)
#define MTU3_CFG_UVW_SUPPORT_ENABLE    (3)
#define MTU3_CFG_MULTIPLEX_INTERRUPT_SUPPORTED (0)
#if MTU3_CFG_MULTIPLEX_INTERRUPT_SUPPORTED
  #define MTU3_CFG_MULTIPLEX_INTERRUPT_ENABLE        BSP_INTERRUPT_ENABLE
  #define MTU3_CFG_MULTIPLEX_INTERRUPT_DISABLE       BSP_INTERRUPT_DISABLE
#else
#define MTU3_CFG_MULTIPLEX_INTERRUPT_ENABLE
#define MTU3_CFG_MULTIPLEX_INTERRUPT_DISABLE
#endif
#endif /* R_MTU3_CFG_H_ */
